VM_NAME: FLARE-VM.Win11.testing
EXPORTED_VM_NAME: FLARE-VM.Win11
SNAPSHOTS:
- extension: ".dynamic"
  description: "Windows 11 VM with FLARE-VM default configuration + idapro.vm"
  cmd: "choco install idapro.vm"
  legal_notice: "legal_notice.txt"
- extension: ".full.dynamic"
  description: "Windows 11 VM with FLARE-VM default configuration + idapro.vm + pdbs.pdbresym.vm + visualstudio.vm"
  cmd: "choco install idapro.vm pdbs.pdbresym.vm visualstudio.vm --execution-timeout 10000"
  legal_notice: "legal_notice.txt"
