name: Build & release vbox

on:
  push:
    tags:
      - 'vbox-*'
  workflow_dispatch: # manual trigger for testing

permissions:
  contents: write

jobs:
  build:
    # use old linux for better portability
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Install build requirements
        run: python -m pip install --upgrade pip setuptools pyinstaller pgi
      - name: Build standalone executable
        run: |
          cd virtualbox

          pyinstaller --onefile --log-level DEBUG vbox-adapter-check.py
          pyinstaller --onefile --log-level DEBUG vbox-clean-snapshots.py

          ls dist
      # Only test vbox-clean-snapshots as vbox-adapter-check uses Notify and it fails in GH actions
      - name: Check  vbox-clean-snapshots runs correctly
        run: virtualbox/dist/vbox-clean-snapshots --help
      - name: Upload binaries to artifacts
        uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4.3.1
        with:
          name: vbox
          path: virtualbox/dist
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@81c65b7cd4de9b2570615ce3aad67a41de5b1a13 # v2.11.2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: virtualbox/dist
          asset_name: vbox
          tag: ${{ github.ref }}
          overwrite: true
          body: "**FLARE-VM does not have releases**, as the project relies on external URLs outside of our control, making it impossible to install an older version. This release only includes binaries for some of the scripts in the [`virtualbox`](https://github.com/mandiant/flare-vm/tree/main/virtualbox) folder to make them easier to use. **To install FLARE-VM check the instructions in the [FLARE-VM README](https://github.com/mandiant/flare-vm)**."

